##It begins
sudo: false

language: python
python: "2.7"

before_script:
  - pip install pytest-cov
  - mkdir $HOME/htmlcov
  - echo "this is a sample artifact" > $HOME/htmlcov/test_artifact.txt

script: ./run_tests.sh
  
addons:
  artifacts:
    # ...
    paths:
    - $HOME/htmlcov
