# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(753, 622)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.open_file = QtGui.QPushButton(self.centralwidget)
        self.open_file.setMinimumSize(QtCore.QSize(155, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/wave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_file.setIcon(icon)
        self.open_file.setObjectName(_fromUtf8("open_file"))
        self.horizontalLayout_2.addWidget(self.open_file)
        self.file_name = QtGui.QLineEdit(self.centralwidget)
        self.file_name.setText(_fromUtf8(""))
        self.file_name.setDragEnabled(True)
        self.file_name.setReadOnly(True)
        self.file_name.setPlaceholderText(_fromUtf8(""))
        self.file_name.setObjectName(_fromUtf8("file_name"))
        self.horizontalLayout_2.addWidget(self.file_name)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.spectr_0 = QtGui.QVBoxLayout()
        self.spectr_0.setObjectName(_fromUtf8("spectr_0"))
        self.spectr_1 = QtGui.QHBoxLayout()
        self.spectr_1.setObjectName(_fromUtf8("spectr_1"))
        self.spectrogram = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrogram.sizePolicy().hasHeightForWidth())
        self.spectrogram.setSizePolicy(sizePolicy)
        self.spectrogram.setObjectName(_fromUtf8("spectrogram"))
        self.spectr_1.addWidget(self.spectrogram)
        self.spectr_y_controls = QtGui.QVBoxLayout()
        self.spectr_y_controls.setObjectName(_fromUtf8("spectr_y_controls"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.spectr_vsb = QtGui.QScrollBar(self.centralwidget)
        self.spectr_vsb.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectr_vsb.sizePolicy().hasHeightForWidth())
        self.spectr_vsb.setSizePolicy(sizePolicy)
        self.spectr_vsb.setBaseSize(QtCore.QSize(0, 0))
        self.spectr_vsb.setOrientation(QtCore.Qt.Vertical)
        self.spectr_vsb.setObjectName(_fromUtf8("spectr_vsb"))
        self.horizontalLayout.addWidget(self.spectr_vsb)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.spectr_y_controls.addLayout(self.horizontalLayout)
        self.y_zoom_in = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_zoom_in.sizePolicy().hasHeightForWidth())
        self.y_zoom_in.setSizePolicy(sizePolicy)
        self.y_zoom_in.setBaseSize(QtCore.QSize(0, 0))
        self.y_zoom_in.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/zoom_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.y_zoom_in.setIcon(icon1)
        self.y_zoom_in.setIconSize(QtCore.QSize(16, 16))
        self.y_zoom_in.setObjectName(_fromUtf8("y_zoom_in"))
        self.spectr_y_controls.addWidget(self.y_zoom_in)
        self.y_zoom_out = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y_zoom_out.sizePolicy().hasHeightForWidth())
        self.y_zoom_out.setSizePolicy(sizePolicy)
        self.y_zoom_out.setBaseSize(QtCore.QSize(0, 0))
        self.y_zoom_out.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/zoom_out.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.y_zoom_out.setIcon(icon2)
        self.y_zoom_out.setObjectName(_fromUtf8("y_zoom_out"))
        self.spectr_y_controls.addWidget(self.y_zoom_out)
        self.spectr_1.addLayout(self.spectr_y_controls)
        self.spectr_0.addLayout(self.spectr_1)
        self.spectr_x_controls = QtGui.QHBoxLayout()
        self.spectr_x_controls.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.spectr_x_controls.setObjectName(_fromUtf8("spectr_x_controls"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem3)
        self.spectr_hsb = QtGui.QScrollBar(self.centralwidget)
        self.spectr_hsb.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectr_hsb.sizePolicy().hasHeightForWidth())
        self.spectr_hsb.setSizePolicy(sizePolicy)
        self.spectr_hsb.setMinimumSize(QtCore.QSize(0, 15))
        self.spectr_hsb.setOrientation(QtCore.Qt.Horizontal)
        self.spectr_hsb.setInvertedAppearance(False)
        self.spectr_hsb.setObjectName(_fromUtf8("spectr_hsb"))
        self.verticalLayout.addWidget(self.spectr_hsb)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem4)
        self.spectr_x_controls.addLayout(self.verticalLayout)
        self.x_zoom_in = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_zoom_in.sizePolicy().hasHeightForWidth())
        self.x_zoom_in.setSizePolicy(sizePolicy)
        self.x_zoom_in.setText(_fromUtf8(""))
        self.x_zoom_in.setIcon(icon1)
        self.x_zoom_in.setObjectName(_fromUtf8("x_zoom_in"))
        self.spectr_x_controls.addWidget(self.x_zoom_in)
        self.x_zoom_out = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x_zoom_out.sizePolicy().hasHeightForWidth())
        self.x_zoom_out.setSizePolicy(sizePolicy)
        self.x_zoom_out.setText(_fromUtf8(""))
        self.x_zoom_out.setIcon(icon2)
        self.x_zoom_out.setObjectName(_fromUtf8("x_zoom_out"))
        self.spectr_x_controls.addWidget(self.x_zoom_out)
        self.spectr_0.addLayout(self.spectr_x_controls)
        self.verticalLayout_2.addLayout(self.spectr_0)
        spacerItem5 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.play = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play.sizePolicy().hasHeightForWidth())
        self.play.setSizePolicy(sizePolicy)
        self.play.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon3)
        self.play.setIconSize(QtCore.QSize(24, 24))
        self.play.setObjectName(_fromUtf8("play"))
        self.horizontalLayout_3.addWidget(self.play)
        self.pause = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause.sizePolicy().hasHeightForWidth())
        self.pause.setSizePolicy(sizePolicy)
        self.pause.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon4)
        self.pause.setIconSize(QtCore.QSize(24, 24))
        self.pause.setObjectName(_fromUtf8("pause"))
        self.horizontalLayout_3.addWidget(self.pause)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/ok.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon5)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 753, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionMotif_Selection = QtGui.QAction(MainWindow)
        self.actionMotif_Selection.setObjectName(_fromUtf8("actionMotif_Selection"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.open_file.setText(_translate("MainWindow", "Open Audio File", None))
        self.pushButton.setText(_translate("MainWindow", "Confirm Selection", None))
        self.actionMotif_Selection.setText(_translate("MainWindow", "Motif Selection", None))

